name: Teranode main test build push

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - staging
      - release/*

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  # Tests and code lint
  test_and_lint:
    uses: ./.github/workflows/teranode_main_tests.yaml
    secrets: inherit

  # Calculate version information
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      git_version: ${{ steps.version.outputs.git_version }}
      git_commit: ${{ steps.version.outputs.git_commit }}
      git_sha: ${{ steps.version.outputs.git_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0  # Fetch all history for tags
      - name: Calculate version
        id: version
        run: ./scripts/determine-git-version.sh

  # Run remote build and deploy workflow
  build-and-deploy:
    needs: calculate-version
    uses: bsv-blockchain/teranode-shared-workflows/.github/workflows/build_and_deploy.yaml@main
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      repository: ${{ github.repository }}
      tag_latest: true
      build_args: |
        DEBUG=true
        GIT_VERSION=${{ needs.calculate-version.outputs.git_version }}
        GIT_COMMIT=${{ needs.calculate-version.outputs.git_commit }}
        GIT_SHA=${{ needs.calculate-version.outputs.git_sha }}
      architectures: '["amd64", "arm64"]'
      runner_labels: '{"amd64":"teranode-runner-16-core","arm64":"teranode-runner-16-core-arm","manifest":"ubuntu-latest"}'
    secrets: inherit

  # Run chain integrity test
  # Disabled for now, since they depend on private teranode-commands/teranode-coinbase packages
  #chainintegrity:
  #  needs: build-and-deploy
  #  uses: ./.github/workflows/chainintegrity-3blasters.yaml
  #  # uses: ./.github/workflows/chainintegrity.yaml
  #  permissions:
  #    contents: read
  #    pull-requests: read
  #    id-token: write
  #    packages: read
  #  secrets: inherit
