name: Teranode PR tests

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  REPO: teranode
  SETTINGS_CONTEXT_DEFAULT: test
  GO_VERSION: "1.25.2"

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: teranode-runner-8-core
    steps:
      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@f974e0c5942f8f37973c4cc395704165fbe629ba # v2
        with:
          theme: "dark"

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: golangci-lint with checkstyle report
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.5.0
          args: --timeout=5m --output.checkstyle.path=golangci-lint-report.xml --output.text.path=stdout

      - name: Upload golangci-lint report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: golangci-lint-report
          path: golangci-lint-report.xml
          retention-days: 1

  test:
    name: test
    runs-on: teranode-runner-16-core
    steps:
      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@f974e0c5942f8f37973c4cc395704165fbe629ba # v2
        with:
          theme: "dark"

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      # Only login to Docker Hub for internal PRs to avoid rate limits.
      # Fork PRs won't have access to secrets and will skip this step.
      - name: Login to Docker Hub
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ vars.DOCKER_ORG }}
          password: ${{ secrets.DOCKER_ORG_TOKEN }}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Run Go tests
        run: make test
        continue-on-error: false

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 1

      # - name: Publish Test Summary Results
      #   if: always()
      #   run: npx github-actions-ctrf ctrf-report.json

  filename-check-report:
    name: filename check report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Generate filename check report
        run: ./scripts/check_filenames.sh

      - name: Upload filename check report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sonar-filename-report
          path: sonar_filename_report.json
          retention-days: 1

